# -*- coding: utf-8 -*-
"""PPG [Darts TCN | Hyperparameter exp] Drug Distribution Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHPcEGfCgvlNVwdN0WYKw94phvYRJM_a
"""

!pip install darts

#pip install --upgrade numpy

#!pip install --upgrade darts

from darts import TimeSeries
from darts.utils.missing_values import fill_missing_values
from darts.dataprocessing.transformers import Scaler
from darts.metrics import mape, rmse, r2_score
from darts.models import TCNModel
import pandas as pd
import numpy as np

#import os
#os.environ["PYDEVD_DISABLE_FILE_VALIDATION"] = "1"

#%env PYDEVD_DISABLE_FILE_VALIDATION=1

df = pd.read_csv("/content/PARIT_PADANG_GLOBAL.csv", sep=';')
df.head()
df

df.info()

df = pd.read_csv('PARIT_PADANG_GLOBAL.csv', sep=';', parse_dates=['Tanggal'], index_col='Tanggal')
df.sort_index()
df.head(10)

df.info()

import pandas as pd

# Baca dan siapkan data
df = pd.read_csv('PARIT_PADANG_GLOBAL.csv', sep=';', parse_dates=['Tanggal'], index_col='Tanggal')
df.index = pd.to_datetime(df.index, format='%d/%m/%Y', errors='coerce')
df = df[['Jumlah']]
df.sort_index(inplace=True)

# Agregasi jumlah per hari jika ada duplikasi tanggal
df = df.groupby(df.index).sum()

# Buat tanggal lengkap dari 1 Jan 2021 sampai 31 Des 2024
full_range = pd.date_range(start='2021-01-01', end='2024-12-31', freq='D')

# Reindex dataframe ke rentang lengkap, isi jumlah yang tidak ada dengan 0
df_full = df.reindex(full_range, fill_value=0)

# Tambahkan kolom penanda apakah data asli atau hasil pelengkapan
df_full['Status'] = ['Asli' if date in df.index else 'Tambahan' for date in df_full.index]

# Rename index jadi 'Tanggal' kembali jika diperlukan
df_full.index.name = 'Tanggal'

# Tampilkan beberapa baris awal dan akhir sebagai contoh
print(df_full.head())
print(df_full.tail())

df_full.info()

df.describe().round()

df.plot()

df.info()

"""# Preprocessing"""

df.sort_index(inplace=True)
df = df[['Jumlah']]

# Pastikan index berupa DatetimeIndex
print(df.index)  # Harus berupa DatetimeIndex
print(df.dtypes)  # Pastikan 'Jumlah' bertipe numerik

df.info()

# Convert index ke DatetimeIndex dengan format yang benar
df.index = pd.to_datetime(df.index, format='%d/%m/%Y', errors='coerce')

# Group by Tanggal untuk menghindari duplikasi (pilih sum atau mean sesuai kebutuhan)
df = df.groupby(df.index).sum()

# Cek hasilnya
print(df.index)  # Harus sudah dalam format DatetimeIndex
print(df.head())  # Cek apakah datanya sudah tersusun dengan baik

df.info()

# Buat rangkaian tanggal lengkap dari tanggal pertama sampai terakhir
all_dates = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')

# Reindex dataframe untuk mengisi tanggal kosong
df = df.reindex(all_dates, fill_value=0)

import matplotlib.pyplot as plt
series = TimeSeries.from_dataframe(df, time_col=None, value_cols="Jumlah",fill_missing_dates=True, freq='D')
series = fill_missing_values(series)
plt.figure(figsize=(50, 5))
series.plot()
plt.show()

df.describe()

import pandas as pd

# Tambahkan kolom 'Tahun' dari index
df['Tahun'] = df.index.year

# Statistik deskriptif lengkap per tahun
desc_stats = df.groupby('Tahun')['Jumlah'].describe()[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]

print(desc_stats)

desc_stats.to_excel('statistik_deskriptif_pertahun_ppg.xlsx')

import pandas as pd

# Pastikan kolom tanggal udah datetime
df['Tanggal'] = pd.to_datetime(df['Tanggal'])
df['tahun'] = df['Tanggal'].dt.year

# Ambil kolom 'jumlah' atau apapun kolom targetmu
desc_stats = df.groupby('tahun')['Jumlah'].describe()[['mean', '50%', 'min', 'max', 'std']]
desc_stats.rename(columns={'50%': 'median'}, inplace=True)

print(desc_stats)

from darts import TimeSeries
from darts.utils.missing_values import fill_missing_values
import matplotlib.pyplot as plt
df_full['Jumlah_MA'] = df_full['Jumlah'].rolling(window=7, min_periods=1).mean()
series_smoothed = TimeSeries.from_dataframe(df_full, time_col=None, value_cols='Jumlah_MA', fill_missing_dates=True, freq='D')

# Plot untuk lihat hasilnya
plt.figure(figsize=(20, 5))
plt.plot(df.index, df["Jumlah"], label="Original", alpha=0.5)
plt.plot(df.index, df["Jumlah_MA"], label="Moving Average (7 hari)", color='navy')
plt.title("Original vs Smoothed")
plt.legend()
plt.show()

from darts import TimeSeries
from darts.utils.missing_values import fill_missing_values
import matplotlib.pyplot as plt
import pandas as pd

# Hitung moving average 7 hari
df_full['Jumlah_MA'] = df_full['Jumlah'].rolling(window=7, min_periods=1).mean()

# Buat TimeSeries dari hasil smoothing (optional, untuk modeling nanti)
series_smoothed = TimeSeries.from_dataframe(df_full, time_col=None, value_cols='Jumlah_MA', fill_missing_dates=True, freq='D')

# Plot perbandingan
plt.figure(figsize=(20, 5))
plt.plot(df_full.index, df_full["Jumlah"], label="Original", alpha=0.5)
plt.plot(df_full.index, df_full["Jumlah_MA"], label="Moving Average (7 hari)", color='navy')
plt.title("Original vs Smoothed")
plt.legend()
plt.show()

# Buat tabel perbandingan
df_perbandingan = df_full[['Jumlah', 'Jumlah_MA']].copy()
df_perbandingan.rename(columns={
    'Jumlah': 'Jumlah (Asli)',
    'Jumlah_MA': 'Jumlah (Smoothed)'
}, inplace=True)

# Tampilkan contoh isi tabel
print(df_perbandingan.head())
print(df_perbandingan.tail())
# Opsional: simpan ke CSV
df_perbandingan.to_csv("perbandingan_data_asli_vs_smoothing.csv")

from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler
from darts.utils.missing_values import fill_missing_values
import matplotlib.pyplot as plt
import pandas as pd

# Buat kolom moving average 7 hari
df_full['Jumlah_MA'] = df_full['Jumlah'].rolling(window=7, min_periods=1).mean()

# Buat time series dari data smoothed (Jumlah_MA)
series_smoothed = TimeSeries.from_dataframe(df_full, value_cols='Jumlah_MA', fill_missing_dates=True, freq='D')

# Normalisasi menggunakan MinMaxScaler
scaler = Scaler()
series_normalized = scaler.fit_transform(series_smoothed)

# Plot ketiga hasil: original, smoothed, normalized
plt.figure(figsize=(20, 6))

plt.plot(df_full.index, df_full['Jumlah'], label='Original', alpha=0.4)
plt.plot(df_full.index, df_full['Jumlah_MA'], label='Smoothed (MA7)', color='navy', linewidth=2)
plt.plot(series_normalized.time_index, series_normalized.values().squeeze(), label='Normalized (0–1)', color='orange', linestyle='--')

plt.title("Original vs Smoothed vs Normalized Data")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from darts import TimeSeries
import matplotlib.pyplot as plt
# Normalisasi smoothed series (bukan data mentah)
scaler = Scaler()  # default pakai MinMaxScaler di balik layar
series_scaled = scaler.fit_transform(series_smoothed)

# Plot hasil normalisasi
plt.figure(figsize=(20, 5))
series_scaled.plot(label="Scaling", color='navy')
plt.title("MinMaxScaler")
plt.legend()
plt.show()

from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler
import pandas as pd

# Normalisasi smoothed series
scaler = Scaler()  # default pakai MinMaxScaler
series_scaled = scaler.fit_transform(series_smoothed)

# Konversi keduanya ke DataFrame
df_before = series_smoothed.to_dataframe().rename(columns={series_smoothed.columns[0]: 'Jumlah (Sebelum)'})
df_after = series_scaled.to_dataframe().rename(columns={series_scaled.columns[0]: 'Jumlah (Setelah)'})

# Gabungkan keduanya berdasarkan index (tanggal)
df_comparison = pd.concat([df_before, df_after], axis=1)

# Tampilkan 5 baris pertama sebagai preview
print(df_comparison.head(7).round(4))

# Optional: simpan ke CSV
#df_comparison.to_csv("data_sebelum_dan_sesudah_normalisasi.csv")

df.info()

df

from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(df['Jumlah_MA'], model='additive', period=7)
plt.figure(figsize=(50, 5))
result.plot()

from statsmodels.tsa.seasonal import STL
import matplotlib.pyplot as plt

# Lakukan dekomposisi
stl = STL(df["Jumlah_MA"], period=30)  # Ganti 30 dengan periode dugaan (misal, 30 hari kalau bulanan)
result = stl.fit()

# Plot hasilnya
result.plot()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt

# Lakukan dekomposisi
decomposition = seasonal_decompose(df['Jumlah_MA'], period=30)  # Sesuaikan periodenya

# Buat plot dengan warna yang lebih soft
fig, axes = plt.subplots(4, 1, figsize=(8, 6), sharex=True)

# Warna soft & gentle
colors = ["black", "blue", "green", "orange"]  # Navy, Teal, Lavender, Soft Brown

# Plot tiap komponen dengan warna lebih lembut
decomposition.observed.plot(ax=axes[0], title='Observed', color=colors[0])
decomposition.trend.plot(ax=axes[1], title='Trend', color=colors[1])
decomposition.seasonal.plot(ax=axes[2], title='Seasonal', color=colors[2])
decomposition.resid.plot(ax=axes[3], title='Residual', color=colors[3])

# Tambahkan grid tipis agar lebih clean
for ax in axes:
    ax.grid(linestyle="dashed", alpha=0.5)

plt.tight_layout()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt

# Lakukan dekomposisi
decomposition = seasonal_decompose(df['Jumlah'], model='additive', period=30)

# Buat figure dengan 3 subplot
fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(20, 8))

    # Plot 1: Grafik penyaluran harian
ax1.plot(df.index, df['Jumlah'], label='Penyaluran', color='blue')
ax1.set_title(f'Penyaluran')
ax1.grid(False)
ax1.legend(loc='upper right', frameon=True)

decomposition = seasonal_decompose(df['Jumlah'], model='additive', period=30)

        # Plot trend mingguan
ax2.plot(decomposition.trend, label='Trend', color='blue')
ax2.grid(False)
ax2.legend(loc='upper right', frameon=True)

        # Plot seasonal mingguan
ax3.plot(decomposition.seasonal, label='Seasonal', color='blue')
ax3.grid(False)
ax3.legend(loc='upper right', frameon=True)
for ax in [ax1, ax2, ax3]:
    for spine in ax.spines.values():
        spine.set_visible(True)
#ax1.legend(loc='upper right', frameon=True)
#ax2.legend(loc='upper right', frameon=True)
#ax3.legend(loc='upper right', frameon=True)



# Hapus spacing judul/teks tambahan
plt.tight_layout()
plt.show()

decomposition = seasonal_decompose(df['Jumlah_MA'], period=30) # Sesuaikan dengan pola yang dicurigai (misal 7 hari)
plt.subplots(figsize=(12, 3))

decomposition.observed.plot(title='Observed', color='blue')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Penyaluran')
plt.tight_layout()
plt.grid(True)
plt.show()

plt.figure(figsize=(20, 5))
plt.plot(df["Jumlah_MA"], label="Observe", color='blue')

plt.legend()
plt.xlabel("Tanggal")
plt.ylabel("Jumlah Penyaluran")
plt.title("SObserve")
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Misalnya, df['value'] adalah data aslinya
df['MA_7'] = df['Jumlah'].rolling(window=7).mean()
df['MA_14'] = df['Jumlah'].rolling(window=14).mean()
df['MA_30'] = df['Jumlah'].rolling(window=30).mean()

# Plot hasil smoothing dengan berbagai window size
plt.figure(figsize=(18, 6))
plt.plot(df.index, df['Jumlah'], label='Original', color='gray', alpha=0.5)
plt.plot(df.index, df['MA_7'], label='7-day MA', color='blue')
plt.plot(df.index, df['MA_14'], label='14-day MA', color='green')
plt.plot(df.index, df['MA_30'], label='30-day MA', color='red')

plt.legend()
plt.title('Comparison of Moving Averages (7, 14, 30 days)')
plt.xlabel('Time')
plt.ylabel('Value')
plt.show()

df

df.info()

"""# ACF, PACF for Lag Check"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

# Resample to daily frequency and fill missing dates with 0
#daily_data = df.resample('D').sum().fillna(0)

# Plot the distribution of data
plt.figure(figsize=(20, 5))
plt.plot(df, marker='o', linestyle='-')
plt.title('Distribusi Penyaluran Obat Harian')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Penyaluran')
plt.grid(True)
plt.show()

# Plot ACF to detect seasonality
plt.figure(figsize=(20, 5))
plot_acf(df['Jumlah'], lags=30)
plt.title('Autocorrelation Function (ACF)')
plt.xlabel('Lag (days)')
plt.ylabel('Autocorrelation')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf


# Agregasi data mingguan
weekly_data = df['Jumlah'].resample('W').sum()

# Agregasi data bulanan
monthly_data = df['Jumlah'].resample('M').sum()

# Plot ACF mingguan dan bulanan
fig, axes = plt.subplots(1, 3, figsize=(10, 3))

#ACF harian
#plt.figure(figsize=(20, 5))
plot_acf(df['Jumlah'], ax=axes[0], lags=30)
axes[0].set_title('ACF Daily')
axes[0].set_xlabel('Lag (days)')
axes[0].set_ylabel('Autocorrelation')
#axes[0].set_show()

# ACF mingguan
plot_acf(weekly_data, ax=axes[1], lags=30)
axes[1].set_title('ACF Weekly')
axes[1].set_xlabel('Lag (weeks)')
axes[1].set_ylabel('Autocorrelation')

# ACF bulanan
plot_acf(monthly_data, ax=axes[2], lags=12)
axes[2].set_title('ACF Monthly')
axes[2].set_xlabel('Lag (months)')
axes[2].set_ylabel('Autocorrelation')

plt.tight_layout()
plt.show()

df

"""# TCN Model Build"""

#splitting data
#train, test = series_scale.split_after(pd.Timestamp('20230901'))
from darts import TimeSeries

# Pastikan series_scale adalah TimeSeries
#series_scale = TimeSeries.from_dataframe(df, time_col="time", value_cols="Jumlah")
train, test = series_smoothed.split_after(pd.Timestamp("2024-08-01"))
# Misalnya split 80% training, 20% testing
#train_size = int(0.8 * len(series_smoothed))
#train_data = series_smoothed[:train_size]
#test_data = series_smoothed[train_size:]

"""## 7 days [3, 2, 2] = 7"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=7,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=3,
    num_filters=32,
    num_layers=2,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 7, Kernel =3, No. Blocks = 2, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 7 days [2,3,2] = 8"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=7,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=2,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 7, Kernel =2, No. Blocks = 3, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 14 days [2,3,3] = 14"""

# Inisialisasi Model TCN
model = TCNModel(
    input_chunk_length=14,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=3,
    kernel_size=2,
    num_filters=32,
    num_layers=3,
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)
# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 14, Kernel =2, No. Blocks = 3, Dilation Base= 3")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 14 days [3,3,2] = 15"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=14,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=3,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3}
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 14, Kernel =3, No. Blocks = 3, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 21 days [2,4,2] = 16"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=21,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=2,
    num_filters=32,
    num_layers=4,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 21, Kernel =2, No. Blocks = 4, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 21 days [4,3,2] = 22"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=21,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=4,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)
# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 21, Kernel =4, No. Blocks = 3, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 30 days [3,3,3] = 27"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=30,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=3,
    kernel_size=3,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)
# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 30, Kernel =3, No. Blocks = 3, Dilation Base= 3")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""## 30 days [3,4,2] = 31"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=30,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=3,
    num_filters=32,
    num_layers=4,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

from datetime import timedelta
pred_series = model.historical_forecasts(
    series=train.append(test), # prediksi dari akhir train sampai akhir test
    start=train.end_time() + timedelta(days=1),
    forecast_horizon=1,
    retrain=False,
    stride=1,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np
#pred_series = model.predict(n=len(test), series=train)
# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 7, Kernel =3, No. Blocks = 2, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

# Iterative Learning Forecast ke 2025 (7 hari)
from darts import concatenate
forecast_2025 = []
future_series_2025 = test.copy()  # mulai dari data test terakhir

for i in range(12):  # Prediksi 7 hari
    # Retrain model dengan data terbaru
    model.fit(future_series_2025)  # retrain model pakai data sampai titik ini
    next_pred = model.predict(n=1, series=future_series_2025)  # prediksi hari ke i
    forecast_2025.append(next_pred)  # simpan hasil prediksi
    future_series_2025 = future_series_2025.append(next_pred)  # tambahkan prediksi ke data untuk retrain berikutnya

# Gabungkan hasil prediksi masa depan
forecast_2025_series = concatenate(forecast_2025)

# Plot hasil prediksi ke 2025
plt.figure(figsize=(15, 3))
train.plot(label='Train Data')
test.plot(label='Test Data')
forecast_2025_series.plot(label='Iterative Forecast 2025 (7 Hari)', linewidth=2, linestyle='dashed')
plt.title("Iterative Learning Forecasting ke 2025 (7 Hari)")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

import pandas as pd

# Konversi TimeSeries ke DataFrame
df_forecast = forecast_2025_series.to_dataframe()  # Sesuai peringatan deprecation

# Ambil tiga angka pertama dari setiap nilai
df_forecast = df_forecast.applymap(lambda x: int(str(int(x))[:3]))

# Cetak tabel untuk 4 minggu pertama tahun 2025
print(df_forecast)

# Forecasting data
from datetime import timedelta
#pred_series = model.predict(n=len(test), series=train)
pred_series = model.historical_forecasts(
    series=test,
    forecast_horizon=1,
    retrain=False,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 30, Kernel =3, No. Blocks = 4, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=21,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=3,
    kernel_size=3,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

# Forecasting data
from datetime import timedelta
#pred_series = model.predict(n=len(test), series=train)
pred_series = model.historical_forecasts(
    series=test,
    forecast_horizon=1,
    retrain=False,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Drug Distribution Prediction")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=30,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=3,
    num_filters=32,
    num_layers=4,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)

# Training model TCN
history = model.fit(train, verbose=True)

# Forecasting data
from datetime import timedelta
#pred_series = model.predict(n=len(test), series=train)
pred_series = model.historical_forecasts(
    series=test,
    forecast_horizon=1,
    retrain=False,
    verbose=True
)

import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Drug Distribution Prediction")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

# Forecast 30 hari ke depan (mulai dari data terakhir training + test)
forecast_30 = model.predict(n=180, series=series_smoothed)  # pakai full series

# Plot hasil prediksi
plt.figure(figsize=(20, 4))
series_smoothed.plot(label="Historical Data", linewidth=2)
forecast_30.plot(label="Forecast (Next 30 days)", linestyle="--", linewidth=2)
plt.title("Forecast 30 Hari ke Depan")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah Penyaluran")
plt.legend()
plt.show()

"""#Forecasting 3 Months

Dipilih 14 days kernel 3, layer 2 dan dilation base 2 karena nilai NMSE paling rendah, maka akan dilakukan forecasting mingguan
"""

# Inisialisasi Model TCN
from torch.nn import MSELoss
model = TCNModel(
    input_chunk_length=30,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=3,
    kernel_size=3,
    num_filters=32,
    num_layers=3,
    weight_norm=True,  # Tambahkan weight normalization
    optimizer_kwargs={'lr': 1e-3},
    #random_state=42
)
# Training model TCN
history = model.fit(train, verbose=True)
# Forecasting data
from datetime import timedelta
#pred_series = model.predict(n=len(test), series=train)
pred_series = model.historical_forecasts(
    series=test,
    forecast_horizon=1,
    retrain=False,
    verbose=True
)
import matplotlib.pyplot as plt
from darts.metrics import mse, rmse, smape, mae
import numpy as np

# Plot hasil prediksi vs data aktual
plt.figure(figsize=(15, 3))
# Plot data aktual setelah inverse transform
test.plot(label="Actual Data", linewidth=2)
# Plot data prediksi setelah inverse transform
pred_series.plot(label="Predicted Data", linewidth=2, linestyle='dashed')
plt.title("Input_length = 21, Kernel =4, No. Blocks = 3, Dilation Base= 2")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Fungsi untuk menghitung WAPE
def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100  # Dalam persen

# Konversi ke numpy array untuk evaluasi
pred_np = pred_series.values().flatten()
actual_np = test.values().flatten()

# Pastikan panjangnya sama
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

# Hitung NMSE (MSE dinormalisasi dengan varians data aktual)
mse_value = mse(pred_series, test)
nmse_value = mse_value / np.var(actual_np)

# Hitung MAE dan NMAE
mae_value = mae(pred_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))  # Pakai abs biar tidak kena nilai negatif
mae_absolute = np.mean(np.abs(actual_np - pred_np))  # MAE absolut tambahan

# Hitung metrik evaluasi
wape_value = wape(actual_np, pred_np)
rmse_value = rmse(pred_series, test)
smape_value = smape(pred_series, test)

# Cetak hasil evaluasi
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

import os
import pickle
import json
from datetime import datetime

# Buat folder untuk simpan model
os.makedirs('models', exist_ok=True)
os.makedirs('config', exist_ok=True)

# 1. SIMPAN TCN MODEL (sudah trained)
model_path = 'models/tcn_model_ppg.pth'
model.save(model_path)
print(f"TCN Model disimpan di: {model_path}")

# 2. SIMPAN SCALER
scaler_path = 'models/scaler.pkl'
with open(scaler_path, 'wb') as f:
    pickle.dump(scaler, f)
print(f"Scaler disimpan di: {scaler_path}")

# 3. SIMPAN SERIES YANG SUDAH DI-SMOOTH (untuk referensi)
series_path = 'models/series_smoothed.pkl'
with open(series_path, 'wb') as f:
    pickle.dump(series_smoothed, f)
print(f"Series smoothed disimpan di: {series_path}")

# 4. SIMPAN KONFIGURASI MODEL
config = {
    'model_type': 'TCNModel',
    'input_chunk_length': 30,
    'output_chunk_length': 1,
    'n_epochs': 50,
    'dropout': 0.1,
    'batch_size': 64,
    'dilation_base': 3,
    'kernel_size': 3,
    'num_filters': 32,
    'num_layers': 3,
    'weight_norm': True,
    'optimizer_lr': 1e-3,
    'ma_window': 7,
    'split_date': '2024-08-01',
    'forecast_horizon': 1,
    'data_column': 'Jumlah',
    'saved_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
}

config_path = 'config/model_config_ppg.json'
with open(config_path, 'w') as f:
    json.dump(config, f, indent=4)
print(f"Konfigurasi disimpan di: {config_path}")

print("\n✅ Semua komponen berhasil disimpan!")

plt.figure(figsize=(10, 3))
train.plot(label="Train Data")
test.plot(label="Test Data")
plt.legend()
plt.show()

# Prediksi 28 hari ke depan
n_future = 28

# Siapkan window awal dari test data
last_window = test[-90:]

# Inisialisasi list untuk prediksi
future_predictions = []

# Prediksi 28 hari ke depan secara rekursif
for _ in range(n_future):
    # Prediksi 1 langkah ke depan
    next_pred = model.predict(n=1, series=last_window)

    # Simpan prediksi
    future_predictions.append(next_pred)

    # Update window dengan menambahkan prediksi terakhir
    last_window = last_window[1:].append(next_pred)

# Gabungkan prediksi menjadi satu TimeSeries
future_forecast = future_predictions[0]
for pred in future_predictions[1:]:
    future_forecast = future_forecast.concatenate(pred)


# Visualisasi
plt.figure(figsize=(15, 4))
test.plot(label="Actual Data", linewidth=2, color='black')
pred_series.plot(label="Predicted Data (Test Set)", linestyle='dashed', linewidth=1.5, color='blue')
future_forecast.plot(label="Future Forecast (30 Days)", linestyle='dotted', linewidth=1.5, color='purple')

plt.title("Drug Distribution Prediction for Next 30 Days")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.show()

# Prediksi 28 hari ke depan
n_future = 34

# Siapkan window awal dari test data
last_window = test[-30:]

# Inisialisasi list untuk prediksi
future_predictions = []

# Prediksi 28 hari ke depan secara rekursif
for _ in range(n_future):
    # Prediksi 1 langkah ke depan
    next_pred = model.predict(n=1, series=last_window)

    # Simpan prediksi
    future_predictions.append(next_pred)

    # Update window dengan menambahkan prediksi terakhir
    last_window = last_window[1:].append(next_pred)

# Gabungkan prediksi menjadi satu TimeSeries
future_forecast = future_predictions[0]
for pred in future_predictions[1:]:
    future_forecast = future_forecast.concatenate(pred)


# Visualisasi
plt.figure(figsize=(15, 4))
test.plot(label="Actual Data", linewidth=2, color='black')
pred_series.plot(label="Predicted Data (Test Set)", linestyle='dashed', linewidth=1.5, color='blue')
future_forecast.plot(label="Future Forecast (30 Days)", linestyle='dotted', linewidth=1.5, color='purple')

plt.title("Drug Distribution Prediction for Next 30 Days")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.show()

from darts import concatenate

# Prediksi 30 hari ke depan
n_future = 30

# Gunakan jendela terakhir sepanjang input_chunk_length
input_len = model.input_chunk_length
last_window = test[-90:]  # pastikan panjang cukup

# Inisialisasi list untuk prediksi
future_predictions = []

# Prediksi 1 langkah ke depan sebanyak n_future
for _ in range(n_future):
    next_pred = model.predict(n=1, series=last_window)

    future_predictions.append(next_pred)

    # Geser window: buang 1 titik lama, tambah 1 prediksi
    last_window = last_window[1:].append(next_pred)

# Gabungkan semua prediksi
future_forecast = concatenate(future_predictions)


# Visualisasi
plt.figure(figsize=(15, 4))
series_smoothed.plot(label="Actual Data", linewidth=2, color='black')
test.plot(label="Predicted Data (Test Set)", linestyle='dashed', linewidth=1.5, color='blue')
future_forecast.plot(label="Future Forecast (30 Days)", linestyle='dotted', linewidth=1.5, color='purple')

plt.title("Drug Distribution Prediction for Next 30 Days")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.show()

df_forecast = forecast_2025_series.to_dataframe()
df_forecast = df_forecast.applymap(lambda x: int(str(int(x))[:3]))
print(df_forecast)

import pandas as pd

# Konversi TimeSeries ke DataFrame
df_forecast = future_forecast.to_dataframe()  # Sesuai peringatan deprecation

# Ambil tiga angka pertama dari setiap nilai
df_forecast = df_forecast.applymap(lambda x: int(str(int(x))[:3]))

# Cetak tabel untuk 4 minggu pertama tahun 2025
print(df_forecast)

# ---- Original code (unchanged) ----
# [Keep everything until the visualization part]

# ---- New visualization: Weekly from October ----
plt.figure(figsize=(12, 5))

# Plot ORIGINAL data but resample to weekly
test.resample('W').max().plot(label="Actual Data", linewidth=2, color='black')
pred_series.resample('W').max().plot(label="Predicted (Test Set)", linestyle='dashed', linewidth=1.5, color='blue')
future_forecast.resample('W').max().plot(label="Forecast (Next 4 Weeks)", linestyle='dotted', linewidth=1.5, color='purple')

# Focus on October onward
plt.xlim([pd.Timestamp('2024-11-01'), future_forecast.time_index[-1]])  # Adjust year if needed

# Formatting
plt.title("Weekly Distribution Prediction (Oct 2023 - Present)")
plt.xlabel("Tanggal (Per Minggu)")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()# Potong future_forecast hanya 14 hari pertama
future_forecast_14days = TimeSeries.from_times_and_values(
    future_forecast.time_index[:14],
    future_forecast.values()[:14]
)

# Visualisasi
plt.figure(figsize=(15, 4))
test.plot(label="Actual Data", linewidth=2, color='black')
future_forecast_14days.plot(label="Future Forecast (14 Days)", linestyle='dotted', linewidth=1.5, color='purple')
plt.title("Drug Distribution Prediction for Next 14 Days")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.grid(True)
plt.show()

# 1. Ensure consistent datetime formatting
#

# 2. Create proper date range for forecast
#forecast_dates = pd.date_range(
 ##  periods=28,  # 4 weeks
   # freq='D'
#)

# 3. Convert forecast to TimeSeries with aligned dates


# 4. Plot with proper connection
import matplotlib.dates as mdates
plt.figure(figsize=(12, 6))

# Plot last 60 days of historical data for context
last_60_days = test[-60:]
last_60_days.plot(label="Historical Data", color="blue", lw=2)

# Plot forecast
future_forecast.plot(label="A Month Forecast", color="red", linestyle="--", lw=2)

# Highlight connection point
connection_time = last_60_days.end_time()
connection_value = last_60_days.values()[-1][0]
plt.plot(connection_time, connection_value, 'go', markersize=10, label="Forecast Start")

# Formatting
plt.title("Drug Distribution Forecast", fontsize=14)
plt.ylabel("Jumlah", fontsize=12)
plt.xlabel("Tanggal", fontsize=12)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
plt.xticks(rotation=45)
plt.grid(True, linestyle=":")
plt.legend()
plt.tight_layout()
plt.show()

print("Actual data shape:", last_actual.values().shape)
print("Forecast shape:", future_forecast_inv.values()[:28].shape)

print("Last actual date:", last_actual.end_time())
print("First forecast date:", forecast_dates[0])

#splitting data
#train, test = series_scale.split_after(pd.Timestamp('20230901'))
from darts import TimeSeries

# Pastikan series_scale adalah TimeSeries
#series_scale = TimeSeries.from_dataframe(df, time_col="time", value_cols="Jumlah")
train, test = series_smoothed.split_after(pd.Timestamp("2024-08-01"))
# Misalnya split 80% training, 20% testing
#train_size = int(0.8 * len(series_smoothed))
#train_data = series_smoothed[:train_size]
#test_data = series_smoothed[train_size:]

"""## Recursive

### 7, 3, 2, 2
"""

from darts.metrics import mse, rmse, smape, mae
import numpy as np
import matplotlib.pyplot as plt
from darts import concatenate

from darts.models import TCNModel
from darts.metrics import mse, rmse, smape, mae
import numpy as np
import matplotlib.pyplot as plt

# Inisialisasi Model TCN
model = TCNModel(
    input_chunk_length=7,
    output_chunk_length=1,
    n_epochs=50,
    dropout=0.1,
    batch_size=64,
    dilation_base=2,
    kernel_size=3,
    num_filters=32,
    num_layers=2,
    weight_norm=True,
    optimizer_kwargs={'lr': 1e-3}
)

# ====== Training Model di Train Data ======
model.fit(train, verbose=True)

# Recursive Forecasting di Test Data
forecast_test = []

future_series_test = train.copy()  # start dari data train (seperti validasi real)
for i in range(len(test)):  # looping sepanjang test set
    next_pred = model.predict(n=1, series=future_series_test)  # prediksi 1 hari ke depan
    forecast_test.append(next_pred)
    future_series_test = future_series_test.append(next_pred)  # tambahkan hasil prediksi ke input berikutnya

# Gabungkan hasil prediksi test
forecast_test_series = concatenate(forecast_test)

# Plot hasil prediksi di Test
plt.figure(figsize=(15, 3))
train.plot(label='Train Data')
test.plot(label='Test Data')
forecast_test_series.plot(label='Recursive Forecast Test', linewidth=2, linestyle='dashed')
plt.title("Recursive Forecasting di Test Data (2024)")
plt.xlabel("Tanggal")
plt.ylabel("Jumlah")
plt.legend()
plt.show()

# Evaluasi Test
pred_np = forecast_test_series.values().flatten()
actual_np = test.values().flatten()

# Sesuaikan panjang
if len(actual_np) > len(pred_np):
    actual_np = actual_np[-len(pred_np):]

mse_value = mse(forecast_test_series, test)
nmse_value = mse_value / np.var(actual_np)

mae_value = mae(forecast_test_series, test)
nmae_value = mae_value / np.mean(np.abs(actual_np))
mae_absolute = np.mean(np.abs(actual_np - pred_np))

def wape(y_true, y_pred):
    return (np.abs(y_true - y_pred).sum() / np.abs(y_true).sum()) * 100

wape_value = wape(actual_np, pred_np)
rmse_value = rmse(forecast_test_series, test)
smape_value = smape(forecast_test_series, test)

print("=== Evaluasi Recursive Test Data ===")
print(f"MAE Absolut: {mae_absolute:.4f}")
print(f"MAE (Darts): {mae_value:.4f}")
print(f"NMAE: {nmae_value:.4f}")
print(f"NMSE: {nmse_value:.4f}")
print(f"WAPE: {wape_value:.2f}%")
print(f"RMSE: {rmse_value:.4f}")
print(f"sMAPE: {smape_value:.2f}%")

"""### 7, 2, 3, 2

### 14, 2, 3, 3

### 14, 3, 3, 2

### 21, 4, 3, 2
"""

